version: "3"
services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - kiss-postgres:/var/lib/postgresql/data

  kiss:
    image: guestros/hospital-system-test:latest
    build: ./docker
    depends_on:
      - postgres
    ports:
      - "8080:5000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - SECRET_KEY=tendies123

volumes:
  kiss-postgres: