apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kiss-postgres
  name: kiss-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kiss-postgres
  name: kiss-postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiss-postgres
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kiss-postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          image: postgres:alpine
          name: postgres
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: kiss-postgres-pv
      restartPolicy: Always
      volumes:
        - name: kiss-postgres-pv
          persistentVolumeClaim:
            claimName: kiss-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kiss-postgres
  name: kiss-postgres-service
spec:
  type: ClusterIP
  ports:
    - name: "kiss-psql"
      port: 5432
      targetPort: 5432
  selector:
    app: kiss-postgres